# pip installs everything and runs pytest

name: Python tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'jwt_pydantic/**'
      - 'tests/'
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Flit
        run: python -m pip install flit

      - name: Pip install jwt-pydanitc
        run: |
          pip install .[test]

      - run: pytest --cov=jwt_pydantic/

      - run: mypy jwt_pydantic/
