# pip installs everything and runs pytest

name: Python tests

on:
  pull_request:
    branches:
      - main
    # paths:
    #   - 'jwt_pydantic/**'
    #   - 'tests/'
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    strategy:
      matrix:
        # python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.11"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip install jwt_pydantic
        run: |
          pip install .[test]

      - run: pytest --cov=jwt_pydantic/

      - run: mypy jwt_pydantic/

  twine_publish:
    # if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build jwt_pydantic
        run: |
          python -m pip install build twine
          python -m build

      - name: Publish to pypi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          twine upload --non-interactive --verbose -r testpypi dist/*
